[language-server.pylsp.config.pylsp.plugins]
ruff.enabled = true
black.enabled = true

[language-server.tinymist]
command = "tinymist"
config = { preview.background.enabled = true", preview.background.args = ["--data-plane-host=127.0.0.1:23635", "--invert-colors=never", "--open"] }

[[language]]
name = "typst"
language-servers = ["tinymist"]
auto-format = true
formatter.command = "typstyle"
